
x-common-build:
  build:
    context: O:\\docker_data\

services:

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - backend
      - lab

  frontend:
    build: ../lab4-front
    networks:
      - lab

  app:
    image: nginx:1.27.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.
    depends_on:
      - frontend
      - backend
    networks:
      - lab

volumes:
  pg_data:

networks:
  backend:
  lab: